# Generated by Django 3.2.16 on 2025-06-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0003_auto_20250626_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icecream',
            options={'ordering': ('output_order', 'title'), 'verbose_name': 'мороженое', 'verbose_name_plural': 'Мороженое'},
        ),
    ]
